import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ClientThemeToggle } from "@/components/ui/ClientThemeToggle";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        {/* ThemeToggle debe estar fuera del elemento children para aparecer en todas las páginas */}
        <div id="theme-toggle-wrapper">
          {/* El componente ThemeToggle se importa en un Componente Cliente separado */}
          <ClientThemeToggle />
        </div>
      </body>
    </html>
  );
}
